services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "4001:4001" 
    depends_on:
      - user-service
    networks:
      - booknet

  book-search:
    build:
      context: ./book-search
    ports:
      - "4000:4000" 
    networks:
      - booknet

  user-service:
    build:
      context: ./user-service
    ports:
      - "5000:5000"
    env_file:
      - ./user-service/.env  # Montar el archivo de variables de entorno
    networks:
      - booknet

networks:
  booknet:
    driver: bridge
